### PR TITLE
Fixed Wine Executable Renaming+

### PR DESCRIPTION
**Pull request by Gcenx**
Now Wine Staging/Staging64 have custom names without breaking or causes them to not build all required files.

Added TEMP/TMP to renamedefaults.reg and set to WineSkin user folder, helps when removing user symlinks form Users folder so applications will not break due to deleted symlinked User folder.

fixFrameworksLibraries was trying to link to /usr/lib/libXplugin.1.10.8.dylib as fallback corrected to use the one in the frameworks folder instead.

### CODE REVIEW

**Comment by vitor251093** [comment]
What about the dyld fallback library line? You removed it from the wine run commands. Isn't it necessary for Wineskin to work properly?

> DYLD_FALLBACK_LIBRARY_PATH="${WINESKIN_LIB_PATH_FOR_FALLBACK}"

**Comment by Gcenx** [comment]
Not for me on my end, I even went as far as removing XQuartz from my system and it still worked.
It does not break since once you call anything Launcher directly passes all those arguments to wine.

Take at look in -startWine
It directly handles DYLD_FALLBACK_LIBRARY_PATH
The bash scripts mostly used for custom names is unneeded

**Comment by vitor251093** [comment]
> Removing WINESKIN_LIB_PATH_FOR_FALLBACK from X11 launch will cause WineskinX11 to crash but will load using mac driver, so WINESKIN_LIB_PATH_FOR_FALLBACK, so adding it fixed WineskinX11 launching on El Capitan

I'm not sure if we can remove it then. Maybe it would be better to start a pool in the Porting Team to decide that.

Many Wine/Wineskin users still use El Capitan. I can say that based in PK. About 12% of the users have El Capitan, which is almost the double than Yosemite and below (macOS 10.10 has 4,3%, and from macOS 10.6 to 10.9 there are around 2%).

If we take that direction, we are deciding that the updated Wineskin will only work in macOS 10.12 and above, so only in macOS 10.12 and 10.13, since 10.14 won't support 32 bit processes anymore.

**Comment by vitor251093** [comment]
Ignore my last message. Just checked that you already updated the pull request to keep the support to older systems :)

**Pull request merged**
