### PR TITLE
WineskinX11 removed & Structure changes

### PR DESCRIPTION
**Pull request by Gcenx**
WineskinX11 removed along with options that used it.
XQuartz is now launched on Wrapper creation if installed.
"Release Notes" Now works for 64Bit and Crossover Engines, disabled for Staging.
"Frameworks/bin" removed as it's no longer required
Winery/WineskinLauncher now directly call WineskinLauncher instead of "/Frameworks/bin/Wineskin"
WineskinShutdownScript, WineskinStartupScript & /WineskinMenuScripts" removed, now the 3 scripts along with "WineskinQuit.exe" were moved into "Resources/Scripts" (added to project with any needed edits)

## Current required dylibs with my current tests are as follows;
- libfreetype.6.dylib
- libltdl.7.dylib
- libmpg123.0.dylib
- libpng14.14.dylib
- libpng15.15.dylib
- libpng16.16.dylib

Maybe more are needed but that was all I have needed currently on a system without XQuartz installed using only "Mac Driver"

### CODE REVIEW

**Comment by Gcenx** [comment]
> Although, why is the master wrapper update removing Wineskin Menu Scripts? I mean, it technically is still usable for XQuartz, isn't? The same applies to enable_fake_buttons and option_sends_alt, although I think those two can be easily reproduced in a way that it's also compatible with Mac Driver, in the next release.

These didn't work for me using Mac driver/ XQuartz only seemed to work for WineskinX11, same for fakebuttons/option_sends_alt

But if you can rework them to work with Mac Driver that would be great, I also noticed another option that you added but not used to swap FN keys that sounded very intresting

> Other than that, it seems perfect :D

Thanks.

**Comment by vitor251093** [comment]
> The Menu_Scripts never worked for me using XQuartz so I moved the two usabled things along with the two other Scripts used by Wineskin into "/Scripts". But if you can somehow make it work with XQuartz/Mac Driver that would be way more ideal.

I'm not sure of how they work in X11, so I have no idea of how to support them in XQuartz.

In order to use them in Mac Driver we would need to modify the Wine source, so it isn't a good option unless we can create that feature, make a pull request to Wine, and have it accepted. 

Instead, what is much more likely to be accepted (I think) would be adding the Task Manager, for example, to the Mac Driver menu.

**Comment by vitor251093** [comment]
> I also noticed another option that you added but not used to swap FN keys that sounded very intresting

Ah, yes. I've added that feature to PK. 

Although, I discussed with Paul about that specific feature in the past (back when it was added to PK), and we decided to, instead of submitting that same implementation to Wineskin, to create another layer above WineskinLauncher to use it, so we could use that same implementation in other wrapper-like applications, like Boxer and Amiga wrappers.

The idea behind that was to make that "external wrapper" updatable without the need to update Wineskin or any of the other wrapper-like applications, so we could move some other in-development PK features to that external wrapper, like the joystick support, while still keeping them closed source, like PK is. 

Although, certainly that Fn-feature could be directly added to Wineskin as well. I used a compiled binary of fntoggle to make that feature work:
https://github.com/nelsonjchen/fntoggle

I've compiled it myself in order to make it work in macOS 10.6+. That compiled version can be found inside PK. 

The different between fntoggle and other methods is that it does not require Accessibility permissions to work (although, I haven't tested that in Mojave, and I know some things regarding to Accessibility permissions have changed in that macOS version; PK, for example, could press the Cancel button in the Gecko install window in the past without those permissions, but now it can't).

**Comment by Gcenx** [comment]
Make sense. And thanks for explanation.

So it’s not implemented and considering the issues with Mojave maybe skip the feature.

**Comment by vitor251093** [comment]
> The way Winebottle handles this was adding a system tray icon and add thinks like task manager etc into that menu icon.

> Then we can use that feature in any Wine version.

That seems a very suitable option. And it would be XQuartz and Mac Driver compatible.

The only back-draw is killing the old WineskinMenuScripts support. Since WineskinMenuScripts are split in App and Help categories, supporting them would be a headache.

The old implementation of WineskinLauncher required the WineskinMenuScripts to have even their ordered specified (eg. AppEntry1--Eject Disc, AppEntry2--Task Manager, etc). We could make a single file instead, like WineskinTrayMenu, which has the options name and code instead, so they don't need to be explicitly ordered, like this:

```
[
	{
		"name": "Eject Disc",
		"code": "wine eject"
	},
	{
		"name": "Task Manager",
		"code": "wine start \"C:\\windows\\system32\\taskmgr.exe\""
	},
]
```

I wrote it like a JSON, but it's just an example. I think YML may be more suitable for that, but I don't think there is a native implementation for reading YML files in Objective-C. We could use a framework for that though, if that's the best option.

Also, the first five lines (which are basically present in every script) shouldn't need to be repeated, I think.

```
#!/bin/bash
cd "$(dirname "$0")/../../"
CONTENTSFOLD="$PWD"
export PATH="$CONTENTSFOLD/Frameworks/bin:$CONTENTSFOLD/Frameworks/wswine.bundle/bin:$PATH"
export WINEPREFIX="$CONTENTSFOLD/Resources"
```

**Comment by Gcenx** [comment]
> That seems a very suitable option. And it would be XQuartz and Mac Driver compatible.

Agreed

> The only back-draw is killing the old WineskinMenuScripts support. Since WineskinMenuScripts are split in App and Help categories, supporting them would be a headache.

Yep that's why I just removed them.

> The old implementation of WineskinLauncher required the WineskinMenuScripts to have even their ordered specified (eg. AppEntry1--Eject Disc, AppEntry2--Task Manager, etc). We could make a single file instead, like WineskinTrayMenu, which has the options name and code instead, so they don't need to be explicitly ordered, like this:

Sounds good, also the thing I did like from Winebottler and more why I mentioned it is the task-manager also lists running Windows applications so you can just pick what you want to kill without needing to use the kill command.

**Comment by vitor251093** [comment]
> Sounds good, also the thing I did like from Winebottler and more why I mentioned it is the task-manager also lists running Windows applications so you can just pick what you want to kill without needing to use the kill command.

That's also a possibility.

> Well as long as WineskinLauncher is handling it then yeah I don't think it would need all that anymore, but does it really need to be an editable menu?

There are many utilities for that. One simple example regarding to games: you can add a menu item which launches a mod manager. Also, some companies use Wineskin to create ports of their games (there are some of them even in GOG.com and Steam), and that gives them the possibility to add support links inside the ports. 

And at last, when a port in finished, the ability to kill the processes of a wrapper is still pretty useful, but launching winecfg, regedit or taskmgr may don't be useful at all depending of the mod, and removing them in that case simplifies the menu.

It won't be that hard to implement. I can do that, since I've already made a tray icon for PK, so I already know the path ;)

**Comment by Gcenx** [comment]
> There are many utilities for that. One simple example regarding to games: you can add a menu item which launches a mod manager. Also, some companies use Wineskin to create ports of their games (there are some of them even in GOG.com and Steam), and that gives them the possibility to add support links inside the ports. This is good to make more people know about Wineskin ;)

Yeah that's true I forgot about GOG/Steam ports after the bad one from GOG for TA I gave up on them and just wrap my own now.

> And at last, when a port in finished, the ability to kill the processes of a wrapper is still pretty useful, but launching winecfg, regedit or taskmgr may don't be useful at all depending of the port, and removing them in that case simplifies the menu.

That's true unneeded options could be removed from finished products if it's an editable script.

> It won't be that hard to implement. I can do that, since I've already made a tray icon for PK, so I already know the path ;)

Could you also have it so the Tray icon takes the "MenuBar Name" & "Icon" of the wrapper that would make it super obvious what that icon is todo with said program/game.

OK so I guess we should merge my changed now then right after merge the new readme, then we already have the latest version as "Master" then we can fix the other branchs including legacy etc.

**Comment by vitor251093** [comment]
> Could you also have it so the Tray icon takes the "MenuBar Name" & "Icon" of the wrapper that would make it super obvious what that icon is todo with said program/game.

Yup, I imagined it that way ;)

> OK so I guess we should merge my changed now then right after merge the new readme, then we already have the latest version as "Master" then we can fix the other branchs including legacy etc.

Makes sense for me. Can I merge the pull request now?

**Comment by Gcenx** [comment]
> Makes sense for me. Can I merge the pull request now?

Yeah this then the README update. when I get change near a computer not my phone I see about cleaning up the other branches.

**Pull request merged**
