### PR TITLE
Multiple changes and additions

### PR DESCRIPTION
**Pull request by Gcenx**
- Winetricks silent mode (wineskinlauncer & wineskin.app)

- winetricks - winedebug nologs (wineskinlauncer & wineskin.app)

- Check for XQuartz.app if above 10.8 , if 10.8+ & no XQuartz.app disable related options

- Updated winetricks new version "allfonts" now works again

- WSS-wineserverkill, use winesever kill command instead of "killall" that could corrupt the wrapper

- Removed "Limit CPU to 1 Core" since needed application was removed since 10.7

Plus other fixes/changes

### CODE REVIEW

**Comment by vitor251093** [comment]
About the removal of "Limit CPU to 1 Core": it seems that there is a new method to make it work. Haven't tested it though, but check that: 
https://github.com/ruby/rake/issues/128#issuecomment-211643311

**Comment by Gcenx** [comment]
>About the removal of "Limit CPU to 1 Core": it seems that there is a new method to make it work. Haven't tested it though, but check that:
ruby/rake#128 (comment)

I will check that out, my only real question is I have never had a use for that option and I have never seen mentioned needing to disable the CPU to one core even when using wine on Linux?

>Other than that, everything looks great :)

Thanks,

**Comment by vitor251093** [comment]
> I will check that out, my only real question is I have never seen anywhere mentioning the need to disable down to 1 CPU core to make something use.

I've seen that a couple of times. Although, it only happens with old applications. doh even had to include that feature.

**Comment by Gcenx** [comment]
Ok then, I will add it back just now I don't have space for the checkbox ;(

Is it possible to hide tabs? like I could add another tab and then checkbox to enable/disable an "Advanced" tab then keep anything that normal users would't use could be hidden their?

**Comment by vitor251093** [comment]
> Is it possible to hide tabs? like I could add another tab and then checkbox to enable/disable an "Advanced" tab then keep anything that normal users would't use could be hidden their?

Maybe we don't need to hide it for real. In fact, the third tab is called Options. We could create a 4th tab called Advanced with the options that aren't for normal users. Even because hiding tabs isn't a regular behaviour in macOS, so many people won't even suspect of how to show those options.

**Comment by chrisballinger** [comment]
Howdy @Gcenx! I'm also tracking this PR over here in the new "Wineskin Community" repo: https://github.com/WineskinCommunity/Wineskin/pull/2

I added you to the organization so you should already have write/push access to that repo.

Cheers!

**Comment by Gcenx** [comment]
Yeah I never seen it done on macOS so I wasn't sure it was even possible,

I will just do the original plan like you also said just add the 4th tab called "Advanced", then move items over too it as needed

**Comment by vitor251093** [comment]
> I will just do the original plan like you also said just add the 4th tab called "Advanced", then move items over too it as needed

Great :) As soon as you do that, let me know. I may have a little spare time that week, so I should be able to make the silent installation change. 

By the way, based in what I read in the winetricks file, I think we can "trick" the winetricks file to run into silent mode by adding `-q` before the winetrick names. The Wineskin Launcher should identify it has a winetrick, and add it to the function call.

**Comment by Gcenx** [comment]
>Great :) As soon as you do that, let me know. I may have a little spare time that week, so I should be able to make the silent installation change.

Added the new tab and just reverted the CPU removal for now since I need to see how the other command will works.

>By the way, based in what I read in the winetricks file, I think we can "trick" the winetricks file to run into silent mode by adding -q before the winetrick names. The Wineskin Launcher should identify it has a winetrick, and add it to the function call.

That's basically what I did, using a verbal to control if its used or not

>            if ([[self.portManager plistObjectForKey:WINESKIN_WRAPPER_PLIST_KEY_WINETRICKS_SILENT] intValue] == 1)
>            {
>                silentMode = @"-q";
>            }
>            else
>            {
>                silentMode = @"";
>            }

**Pull request merged**
